/* DPRO TUTORIAL STANDARD V1.1 / DAYCARE / R3 / REPLAY-FOCUS SYNC FIX */
(function dproDaycareTutorial(global){
  'use strict';
  if(!global.document || global.__DPRO_DAYCARE_TUTORIAL_V11__) return;
  global.__DPRO_DAYCARE_TUTORIAL_V11__ = true;

  const VERSION='DPRO-TUTORIAL-DAYCARE-R3-V1.1-20260829';
  const STORAGE_KEY='dpro_daycare_tutorial_state_v11';
  const POSITION_KEY='dpro_daycare_tutorial_position_v11';
  const SAFE_MARGIN=8;
  const STEPS=Object.freeze([
    {id:'DAYCARE-F10-01',route:'/index.html',primary:'.dayservice-operation-demo-banner',fallback:['.topbar','.hero'],title:'公開操作デモの注意を確認',copy:'架空情報だけを使う公開デモであることを最初に確認します。',safe:'表示専用の案内領域です。クリックや送信は行いません。'},
    {id:'DAYCARE-F10-02',route:'/index.html',primary:'.hero',fallback:['.hero-content','#facilityName'],title:'家族向け画面の目的を確認',copy:'お休み・利用日変更・送迎・持ち物・施設連絡をまとめる家族向け入口です。',safe:'表示専用の領域です。業務データは変更しません。'},
    {id:'DAYCARE-F10-03',route:'/index.html',primary:'#credentialSection',fallback:['#phoneInput','#userNumberInput'],title:'本人確認の入力欄を見る',copy:'登録電話番号と利用者番号で本人確認する構成を確認します。実在情報は入力しません。',safe:'入力や送信は自動実行しません。'},
    {id:'DAYCARE-F10-04',route:'/index.html',primary:'#demoFillButton',fallback:['#phoneInput','#userNumberInput'],title:'デモ情報の入口を確認',copy:'架空のデモ利用者情報を使える入口です。チュートリアルはこのボタンを自動で押しません。',safe:'ターゲット表示だけを行います。'},
    {id:'DAYCARE-F10-05',route:'/index.html',primary:'#verifyButton',fallback:['#credentialStatus','#credentialSection'],title:'本人確認ボタンの役割を確認',copy:'本人確認後に送迎・持ち物などの表示へ進む入口です。チュートリアルは自動で押しません。',safe:'本人確認APIや端末保存をチュートリアルから起動しません。'},
    {id:'DAYCARE-F10-06',route:'/index.html',primary:'#quickSection',fallback:['.quick-grid','.quick-card'],title:'かんたんメニュー全体を確認',copy:'家族が使う主要メニューを一覧で確認します。送信系はこのガイドでは実行しません。',safe:'メニューの表示確認だけです。'},
    {id:'DAYCARE-F10-07',route:'/index.html',primary:'[data-panel="transport"]',fallback:['#quickSection','.quick-grid'],title:'送迎時間の確認入口',copy:'次回のお迎え・お帰り予定を確認するread-only導線です。',safe:'送迎の再確認ボタンは自動操作しません。'},
    {id:'DAYCARE-F10-08',route:'/index.html',primary:'[data-panel="items"]',fallback:['#quickSection','.quick-grid'],title:'持ち物の確認入口',copy:'施設からの持ち物案内を見るread-only導線です。',safe:'業務データ更新はありません。'},
    {id:'DAYCARE-F10-09',route:'/index.html',primary:'[data-panel="member"]',fallback:['[data-bottom-action="member"]','#quickSection'],title:'利用者カードの入口',copy:'今後の予定や連絡履歴をまとめて確認する利用者カードへの入口です。',safe:'利用者カードを開くボタンは自動操作しません。'},
    {id:'DAYCARE-F10-10',route:'/index.html',primary:'[data-bottom-action="member"]',fallback:['[data-bottom-action="top"]','.bottom-nav'],title:'下部ナビゲーションを確認',copy:'スマホでも主要導線へ戻れる固定ナビゲーションを確認してFirst10を終了します。',safe:'ローカル表示の確認だけで、外部送信やDB更新はありません。'}
  ]);

  const state={active:false,index:0,target:null,drag:null,lastFocus:null,renderToken:0};
  const $=s=>document.querySelector(s);
  function clamp(v,min,max){return Math.min(Math.max(v,min),Math.max(min,max));}
  function now(){return new Date().toISOString();}
  function readJSON(key,fallback){try{return JSON.parse(global.localStorage.getItem(key)||'')||fallback;}catch(_){return fallback;}}
  function writeJSON(key,value){try{global.localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){return false;}}
  function readState(){const s=readJSON(STORAGE_KEY,null);if(!s||s.version!==VERSION)return null;return s;}
  function saveState(status,index){writeJSON(STORAGE_KEY,{version:VERSION,status,index:clamp(Number(index)||0,0,STEPS.length-1),stepId:STEPS[clamp(Number(index)||0,0,STEPS.length-1)].id,updatedAt:now()});updateLauncher();}
  function clearHighlight(){const h=$('#dpro-tutorial-highlight');if(h){h.style.display='none';}state.target=null;}
  function visible(el){if(!el)return false;const cs=getComputedStyle(el);const r=el.getBoundingClientRect();return cs.display!=='none'&&cs.visibility!=='hidden'&&Number(cs.opacity)!==0&&r.width>0&&r.height>0;}
  function resolveTarget(step){for(const sel of [step.primary,...step.fallback]){let el=null;try{el=$(sel);}catch(_){continue;}if(visible(el))return {el,selector:sel};}return null;}
  function ensureTargetVisible(el){if(!el)return;const r=el.getBoundingClientRect();const pad=18;if(r.top<pad||r.bottom>global.innerHeight-pad||r.left<pad||r.right>global.innerWidth-pad){el.scrollIntoView({behavior:'auto',block:'center',inline:'nearest'});}}
  function updateHighlight(){if(!state.active||!state.target)return;const h=$('#dpro-tutorial-highlight');if(!h)return;const r=state.target.getBoundingClientRect();if(r.bottom<0||r.top>global.innerHeight||r.right<0||r.left>global.innerWidth){h.style.display='none';return;}const left=clamp(r.left-5,2,global.innerWidth-4);const top=clamp(r.top-5,2,global.innerHeight-4);const right=clamp(r.right+5,4,global.innerWidth-2);const bottom=clamp(r.bottom+5,4,global.innerHeight-2);h.style.left=left+'px';h.style.top=top+'px';h.style.width=Math.max(2,right-left)+'px';h.style.height=Math.max(2,bottom-top)+'px';h.style.display='block';}
  function defaultPosition(){const card=$('#dpro-tutorial-card');const w=card?.offsetWidth||360;return {x:clamp(global.innerWidth-w-16,SAFE_MARGIN,global.innerWidth-w-SAFE_MARGIN),y:clamp(84,SAFE_MARGIN,global.innerHeight-(card?.offsetHeight||360)-SAFE_MARGIN)};}
  function applyPosition(pos){const card=$('#dpro-tutorial-card');if(!card)return;const w=card.offsetWidth||Math.min(360,global.innerWidth-24);const h=card.offsetHeight||Math.min(500,global.innerHeight-24);const x=clamp(Number(pos?.x),SAFE_MARGIN,global.innerWidth-w-SAFE_MARGIN);const y=clamp(Number(pos?.y),SAFE_MARGIN,global.innerHeight-h-SAFE_MARGIN);card.style.left=x+'px';card.style.top=y+'px';card.style.right='auto';card.style.bottom='auto';}
  function clampCard(){if(!state.active)return;const card=$('#dpro-tutorial-card');if(!card)return;const r=card.getBoundingClientRect();applyPosition({x:r.left,y:r.top});updateHighlight();}
  function announce(text){const live=$('#dpro-tutorial-live');if(live){live.textContent='';setTimeout(()=>{live.textContent=text;},20);}}
  function renderStep(index,focus=true){state.index=clamp(index,0,STEPS.length-1);const step=STEPS[state.index];const token=++state.renderToken;const resolved=resolveTarget(step);state.target=resolved?.el||null;if(state.target){ensureTargetVisible(state.target);}requestAnimationFrame(()=>{if(token!==state.renderToken)return;updateHighlight();clampCard();});
    $('#dpro-tutorial-kicker').textContent=`STEP ${String(state.index+1).padStart(2,'0')} / ${STEPS.length} · ${step.id}`;
    $('#dpro-tutorial-title').textContent=step.title;$('#dpro-tutorial-copy').textContent=step.copy;$('#dpro-tutorial-safe').textContent=resolved?`対象: ${resolved.selector}｜${step.safe}`:`対象が見つからないため安全にスキップ可能です。｜${step.safe}`;
    $('#dpro-tutorial-count').textContent=`${state.index+1} / ${STEPS.length}`;$('#dpro-tutorial-bar-fill').style.width=`${((state.index+1)/STEPS.length)*100}%`;
    $('#dpro-tutorial-back').disabled=state.index===0;$('#dpro-tutorial-next').textContent=state.index===STEPS.length-1?'完了':'次へ';
    saveState('in_progress',state.index);announce(`${state.index+1}番目、${step.title}`);if(focus){setTimeout(()=>$('#dpro-tutorial-next')?.focus({preventScroll:true}),40);}}
  function focusLauncher(){const launcher=$('#dpro-tutorial-launcher');if(!launcher)return;launcher.focus({preventScroll:true});requestAnimationFrame(()=>{if(document.activeElement!==launcher)launcher.focus({preventScroll:true});});}
  function showTutorial(index){state.lastFocus=document.activeElement;state.active=true;state.drag=null;const card=$('#dpro-tutorial-card');if(!card)return;card.setAttribute('aria-hidden','false');card.innerHTML=card.dataset.stepMarkup;const savedPos=readJSON(POSITION_KEY,null);const initialIndex=clamp(Number(index)||0,0,STEPS.length-1);state.index=initialIndex;applyPosition(savedPos||defaultPosition());renderStep(initialIndex,true);updateLauncher();}
  function pauseTutorial(){if(!state.active)return;const persisted=readState();if(!persisted||!['completed','skipped'].includes(persisted.status))saveState('in_progress',state.index);state.active=false;state.drag=null;clearHighlight();const card=$('#dpro-tutorial-card');card.setAttribute('aria-hidden','true');card.innerHTML='';updateLauncher();focusLauncher();}
  function skipTutorial(){saveState('skipped',state.index);state.active=false;state.drag=null;clearHighlight();const card=$('#dpro-tutorial-card');card.setAttribute('aria-hidden','true');card.innerHTML='';updateLauncher();focusLauncher();}
  function completeTutorial(){saveState('completed',STEPS.length-1);clearHighlight();const card=$('#dpro-tutorial-card');card.innerHTML=`<div class="dpro-tutorial-complete"><p class="dpro-tutorial-kicker">FIRST10 COMPLETE</p><h2>10ステップ完了</h2><p>家族向け画面の安全な主要導線を確認しました。送信・保存・業務更新はチュートリアルから実行していません。</p><div class="dpro-tutorial-complete-actions"><button type="button" id="dpro-tutorial-replay" class="dpro-primary">最初から見る</button><button type="button" id="dpro-tutorial-done">閉じる</button></div></div>`;clearHighlight();updateLauncher();setTimeout(()=>$('#dpro-tutorial-replay')?.focus({preventScroll:true}),30);}
  function replay(){showTutorial(0);}
  function startOrResume(){const s=readState();if(s?.status==='in_progress')showTutorial(s.index);else showTutorial(0);}
  function updateLauncher(){const b=$('#dpro-tutorial-launcher');if(!b)return;const s=readState();if(state.active){b.hidden=true;return;}b.hidden=false;b.textContent=s?.status==='in_progress'?`操作ガイドを再開（${(s.index||0)+1}/10）`:s?.status==='completed'||s?.status==='skipped'?'操作ガイドをもう一度':'操作ガイドを開始';}
  function pointerDown(e){if(e.button!==undefined&&e.button!==0)return;const card=$('#dpro-tutorial-card');const r=card.getBoundingClientRect();state.drag={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,left:r.left,top:r.top};try{e.currentTarget.setPointerCapture(e.pointerId);}catch(_){}e.preventDefault();}
  function pointerMove(e){if(!state.drag||state.drag.pointerId!==e.pointerId)return;const card=$('#dpro-tutorial-card');const x=state.drag.left+(e.clientX-state.drag.startX);const y=state.drag.top+(e.clientY-state.drag.startY);applyPosition({x,y});updateHighlight();e.preventDefault();}
  function pointerUp(e){if(!state.drag||state.drag.pointerId!==e.pointerId)return;const card=$('#dpro-tutorial-card');const r=card.getBoundingClientRect();writeJSON(POSITION_KEY,{x:r.left,y:r.top});state.drag=null;}
  function bind(){document.addEventListener('click',e=>{const id=e.target?.id;if(id==='dpro-tutorial-launcher'){startOrResume();return;}if(!state.active)return;if(id==='dpro-tutorial-next'){if(state.index===STEPS.length-1)completeTutorial();else renderStep(state.index+1);return;}if(id==='dpro-tutorial-back'){renderStep(state.index-1);return;}if(id==='dpro-tutorial-close'){pauseTutorial();return;}if(id==='dpro-tutorial-skip'){skipTutorial();return;}if(id==='dpro-tutorial-replay'){replay();return;}if(id==='dpro-tutorial-done'){pauseTutorial();return;}if(id==='dpro-tutorial-restart'){replay();return;}if(id==='dpro-tutorial-resume'){const s=readState();showTutorial(s?.index||0);return;}});
    document.addEventListener('pointerdown',e=>{if(e.target?.closest?.('.dpro-tutorial-drag-handle'))pointerDown(e);});document.addEventListener('pointermove',pointerMove,{passive:false});document.addEventListener('pointerup',pointerUp);document.addEventListener('pointercancel',pointerUp);
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.active){e.preventDefault();pauseTutorial();return;}if(!state.active)return;if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();if(state.index===STEPS.length-1)completeTutorial();else renderStep(state.index+1);}else if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();renderStep(state.index-1);}});
    global.addEventListener('resize',clampCard);global.addEventListener('scroll',updateHighlight,{passive:true});}
  function build(){const root=document.createElement('div');root.id='dpro-tutorial-root';root.setAttribute('data-version',VERSION);root.innerHTML=`<div id="dpro-tutorial-highlight" aria-hidden="true"></div><section id="dpro-tutorial-card" role="dialog" aria-modal="false" aria-label="DPRO 操作ガイド" aria-hidden="true"></section><div id="dpro-tutorial-live" aria-live="polite"></div>`;document.body.appendChild(root);const card=$('#dpro-tutorial-card');card.dataset.stepMarkup=`<div class="dpro-tutorial-drag-handle" tabindex="0" aria-label="操作ガイドをドラッグして移動"><strong>DPRO 操作ガイド</strong><span class="dpro-tutorial-grip" aria-hidden="true">⠿</span></div><div class="dpro-tutorial-body"><p id="dpro-tutorial-kicker" class="dpro-tutorial-kicker"></p><h2 id="dpro-tutorial-title" class="dpro-tutorial-title"></h2><p id="dpro-tutorial-copy" class="dpro-tutorial-copy"></p><p id="dpro-tutorial-safe" class="dpro-tutorial-safe"></p><div class="dpro-tutorial-progress"><span id="dpro-tutorial-count"></span><div class="dpro-tutorial-bar" aria-hidden="true"><span id="dpro-tutorial-bar-fill"></span></div></div></div><div class="dpro-tutorial-actions"><button type="button" id="dpro-tutorial-skip">スキップ</button><button type="button" id="dpro-tutorial-back">戻る</button><button type="button" id="dpro-tutorial-next" class="dpro-primary">次へ</button></div><div class="dpro-tutorial-tools"><button type="button" id="dpro-tutorial-close">閉じる</button><button type="button" id="dpro-tutorial-restart">最初から</button></div>`;
    const launcher=document.createElement('button');launcher.id='dpro-tutorial-launcher';launcher.type='button';launcher.setAttribute('aria-controls','dpro-tutorial-card');document.body.appendChild(launcher);updateLauncher();}
  function init(){if(!/\/index\.html$/.test(global.location.pathname)&&global.location.pathname!=='/'&&global.location.pathname!=='/dpro-dayservice-line/')return;build();bind();document.documentElement.dataset.dproTutorialVersion=VERSION;global.DPRO_DAYCARE_TUTORIAL={version:VERSION,steps:STEPS,storageKey:STORAGE_KEY,start:()=>showTutorial(0),resume:startOrResume,replay,close:pauseTutorial,getState:readState,getActiveStep:()=>state.active?state.index:null};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
